### ISSUE TITLE
Feature request: provide an option to disable grouping

### ISSUE THREAD

**Issue by Noki** [brianshea2/meshmap.net#10]
I live in Berlin (Germany) and the city covers quite a big area. Currently it is not possible to get a complete view of nodes with exact positions as grouping occours. I would love to see an option to disable grouping or at least have less grouping.

**Comment by brianshea2** [comment]
Grouping / clustering is necessary for browser performance. Without clustering and with the large number of nodes, browsers start to freeze up. This is what Berlin looks like in my browser at the lowest zoom level where no clustering happens. Seems ok to me? It is a trade-off... changing the zoom level at which clustering turns off to a lower level will cause performance issues on lower-end devices. Maybe that level should be configurable by the user or some other solution makes sense here? Keeping this open to brainstorm.

![Screenshot from 2024-06-03 13-13-39](https://github.com/brianshea2/meshmap.net/assets/165865819/692101e5-3172-4a84-b348-3926e2158132)

**Comment by Noki** [comment]
I understand the reasons for grouping, I just wish it would happen less agressively. For Freifunk Berlin we also have a map (https://hopglass.berlin.freifunk.net/) and it shows several hundred nodes without any performance issues. Having the option to configure it or turn it off on demand would also be fine. It would be really nice to have a full map of all nodes without grouping.

Just to clarify: Berlin is quite a bit bigger than your screenshot (https://www.openstreetmap.org/relation/62422) and if you zoom to see all of Berlin at full HD resolution you already have grouping:. 😉

![image](https://github.com/brianshea2/meshmap.net/assets/198902/97b1a08f-51bb-468a-a9fd-33045b23f600)

btw.: the map is a great project and I really like that you opened up the Github repo so people could share thoughts and contribute.

**Comment by brianshea2** [comment]
Temporarily (maybe) testing with a lower zoom level (10 vs 12) at which clustering is disabled. Open to comments.

Ideally I'd like to let the user configure this, but haven't found a great control so far.

**Comment by Noki** [comment]
Works for me now! Thank you.

![image](https://github.com/brianshea2/meshmap.net/assets/198902/7bae8933-e7ac-4c2c-b657-c147df7e1db8)
