### ISSUE TITLE
Request: MQTT Topic to include sub-topics as well

### ISSUE THREAD

**Issue by Mambo430** [brianshea2/meshmap.net#11]
Hello,
Thank you for the amazing work. Would it be possible to include additional sub-topics as well? 
IE. msh/US/FL
Not sure if this would be a modification of the code to be msh/#/# or if there is a wildcard (*) feature in the coding language.

**Comment by brianshea2** [comment]
It already does this :) It subscribes to msh/# and then filters via a regex which allows any number of root subtopics. Are you seeing an issue where this isn't working?
