### ISSUE TITLE
MapReport Ignores Recent Firmware Versions

### ISSUE THREAD

**Issue by Delurkdotcom** [brianshea2/meshmap.net#12]
Hi,

I believe I've identified an issue with a recent commit (e1ec364) that was meant to filter out MapReport spam for firmware version 2.3.1. It appears that this filtering is also inadvertently affecting reports from the newer firmware versions 2.3.10 and 2.3.11, regardless of their posting interval. Specifically, I'm experiencing reporting issues even though I only publish once per hour and my message correctly posts to the topic /msh/2/map. For the past two days, I have not been able to see my nodes at all.

Thanks in advance.

**Comment by brianshea2** [comment]
Oops, you're right! Thank you for reporting this.
