### ISSUE TITLE
region

### ISSUE THREAD

**Issue by og1en** [brianshea2/meshmap.net#14]
I configure from CLI my node. On map it not show my region
![111111](https://github.com/brianshea2/meshmap.net/assets/160345541/6eab6001-dd8a-4fb1-b03d-fca96f823cdb)

How setup my node to show region on map? (And not use root)

**Comment by brianshea2** [comment]
`meshtastic --set mqtt.map_reporting_enabled true`

**Comment by zapewne** [comment]
this node is on map, but not send Region info

**Comment by brianshea2** [comment]
The region information is part of the MapReport message, enabled in the MQTT module. Only nodes reporting directly to MQTT can provide that data. Hope that helps!

**Comment by og1en** [comment]
> The region information is part of the MapReport message, enabled in the MQTT module. Only nodes reporting directly to MQTT can provide that data. Hope that helps!

I 'm trying Your solution. Sorry this not help. Still my node is without many information, region too. Region not send to map ;(
