### ISSUE TITLE
How deleting LongFast

### ISSUE THREAD

**Issue by mix127** [brianshea2/meshmap.net#15]
My node send twice position, one on LongFast and second on Map report
How deleting LongFast sending map report?

```
Last seen	via	root topic	channel
2min ago	self	msh	LongFast
14min ago	self	msh	n/a (MapReport)

```

**Comment by brianshea2** [comment]
The first row is your location reported over your primary channel with MQTT uplink enabled. The second row comes from the map reporting feature of the MQTT module itself.

**Comment by mix127** [comment]
this is not answer.
I know what this text means, but HOW DELETE this longfast?
