### ISSUE TITLE
node not shown on the map

### ISSUE THREAD

**Issue by jranma** [brianshea2/meshmap.net#16]
Hi, 
Not necessarily a problem on your side, but I'm trying to understand why my node doesn't appear on the map. 
The node is alive and well and sends its position, which is then forwarded to the official MQTT server. 
Node ID is: !e564562c
all the more strange as it appears on https://meshtastic.liamcottle.net/

**Comment by brianshea2** [comment]
That node isn't reporting its position anymore. Even Liam's map shows the location was last updated over 9 days ago. MeshMap has much lower expiration times (24 hours) to reduce the noise of inactive nodes on the map.

**Comment by jranma** [comment]
Thanks for the info. Makes sense.
