### ISSUE TITLE
Voltage resolution

### ISSUE THREAD

**Issue by SR7673** [brianshea2/meshmap.net#18]
Hello!
It would be nice if the voltage shown for a node, e.g. "Power 93% (4.1V)" could have a higher resolution, two numbers after the comma. This would allow remote node runners to watch the discharge curve of their system more accurately.
In the app on the phone, there are two numbers after the comma so this information seems to be available to the public...
Regards...

**Comment by brianshea2** [comment]
sounds good to me :)
