### ISSUE TITLE
readme improve

### ISSUE THREAD

**Issue by bialystok** [brianshea2/meshmap.net#2]
Meybe add sobe tutorial. How setup the node for apear in map.
with GPS and without

**Comment by brianshea2** [comment]
I'm not sure this repo is the best place for such a tutorial. Maybe some hints/pointers in the readme, pointing to the official docs.

**Comment by bialystok** [comment]
I think this is a very good place. The documentation shows how to make it work. And here what the different things mean.

What MQTT.root should look like, for example. When the blue lines appear. What a node has to do to appear (or disappear if it doesn't send information) on the map. Itd. 
It's all about how-to documentation on how to set it up.

**Comment by geerlingguy** [comment]
I'd be happy with anywhere, really—right now there's a bit of a dearth of information about how to get started with this kind of thing. At a minimum, it would be nice to have in the README some brief explanation of where this site gets its data from, and a link to how to get your node's info added to that central database.

Honestly, as a Meshtastic noob, I'm not sure if it requires MQTT, or is based on node-to-node communication, or what, but it would be helpful :)

**Comment by djekl** [comment]
@geerlingguy to answer some of your questions…

Q) Where does the data come from?
A) The data comes from the official Meshtastic MQTT server

Q) How do I add my node?
A) Your node is either added by being found and reported by another node on the mesh, thats connected to MQTT with Neighbour reporting enabled. Or by simply having your node connected to MQTT doing the Map Reports etc.

Adding MQTT to your node should only be done as uplink only, and not downlink. Doing the downlink will push MQTT messages and nodes onto your local mesh. This is a touchy subject in some communities.

There are also other maps which are user submitted, such as https://map.mpowered247.com

Discord is a good place to get Meshtastic help and support.

Official Meshtastic Discord - https://discord.com/invite/ktMAKGBnBs

And I am active on the Mpowered247 Discord here - https://discord.gg/TZmxrBmWWh

---

@brianshea2 and @bialystok sorry to hijack the thread, just wanted to offer some answers and support

**Comment by brianshea2** [comment]
Ok, long overdue update just pushed. How's that? Did I miss anything?

Also, fan here of your YT videos, @geerlingguy :)

**Comment by geerlingguy** [comment]
@djekl / @brianshea2 - Nice! Very helpful, and my Dad and I are just getting started after Muzi Works reached out and sent over a couple of their nodes for us to test (I've since bought a bare Heltec V3 as well, and am building my own mesh around south St. Louis :D

So far we both have MQTT disabled, we're hoping to make contact with some people just via LoRa, but I may get at least my 'base' node at the studio on the network soon, would be nice to have it pop up on the map!

**Comment by geerlingguy** [comment]
(Also I think the README has improved quite a bit, maybe enough to consider this issue complete haha).

**Comment by djekl** [comment]
@geerlingguy look forward to the video(s).

I know you both have your ham licenses, but I don't recommend the licensed mode. It disables encryption, and seriously limits your potential contacts. The good thing about the LoRa frequencies is no requirement for a license.

Also here in the UK the 443mhz mesh is dead. It may be the same in the US.
