### ISSUE TITLE
topic msh/ZA/# not showing

### ISSUE THREAD

**Issue by dadecoza** [brianshea2/meshmap.net#22]
Hi meshmap.net team!

Any ideas why we no longer see South African nodes?

Our root topic is msh/ZA.

Example ...
```
msh/ZA/2/map/
```

Thanks,
Johannes

**Comment by brianshea2** [comment]
Due to recent changes to Meshtastic's MQTT service, only root topics corresponding to the [LoRa regions](https://meshtastic.org/docs/configuration/radio/lora/#region) are monitored. See issue #21.
