### ISSUE TITLE
Addition of Frequency Information for the Nodes on the Node Map

### ISSUE THREAD

**Issue by hammyMarc** [brianshea2/meshmap.net#25]
As a meshtastic net participant, it would be helpful to know what frequencies are being used so that I can:
1) Join an active local net.
2) ensure my equipment has the transceiver needed to participate.
3) probably other benefits that I'm not thinking of right away :)

Perhaps just the band(s) upon which each nodes is operating.

**Comment by brianshea2** [comment]
MeshMap can only show the data being sent to it from nodes over MQTT. Most nodes report no data about what frequency they're on. Some nodes send [MapReport](https://buf.build/meshtastic/protobufs/docs/main:meshtastic#meshtastic.MapReport) messages which are shown on the map and include the LoRa region, modem preset, etc., but not specifically any non-default frequencies in use. It's generally suggested the default frequencies be used for any given LoRa region. If you want your nodes to send these MapReport messages, see [here](https://meshtastic.org/docs/configuration/module/mqtt/#map-reporting-enabled).

**Comment by hammyMarc** [comment]
Hey Brian, thanks for your thoughtful response. Some of my inquiry stems from a lack of knowledge about the product. Cheers.
