### ISSUE TITLE
My nodes not showing on map

### ISSUE THREAD

**Issue by i0vt** [brianshea2/meshmap.net#26]
Any ideas why we no longer see nodes in Poland?
My 2 nodes and 3 nodes my friend disapear from map after upgdare meshmap.

Is possible showing how correct setup nodes to showing on map? (Probably problem are with MQTT)

**Comment by mix127** [comment]
do you know of a working configuration?
I'm beginer and have trouble with my node too.

**Comment by brianshea2** [comment]
Github issues aren't a support channel. Seek help in one of the friendly Meshtastic communities such as [r/meshtastic](https://www.reddit.com/r/meshtastic) or Discord.

**Comment by i0vt** [comment]
But I need help with THIS site. retna Not some help regarding meshtastic but how to make it appear on this page.
Who will know better what settings will work on this particular page than the creator?
