### ISSUE TITLE
Filter nodes by Modem Preset

### ISSUE THREAD

**Issue by withoutgettingwet** [brianshea2/meshmap.net#27]
Hi, first of all, love this project!

Would it be feasible to add the ability to filter nodes by their modem preset? Because the various modem presets aren't mutually intelligible, adding the ability to filter out nodes that won't actually be able to relay messages might be a helpful feature. 

I'm also hoping that it might help with the adoption of presets beyond long fast, for more rural areas; seeing as it seems increasingly common to have more than one node!

**Comment by brianshea2** [comment]
Will look into adding filtering by modem preset and LoRa region as reported in MapReports and mqtt topics

**Comment by brianshea2** [comment]
Unfortunately, there's no reliable way to get the modem preset from most nodes. It's included in the MapReport messages, but very few nodes send those (they must be mqtt-connected and enable that option). I was thinking I could use the mqtt topic for the other nodes, but the topic includes the channel name, which only happens to be "LongFast" by default, and can be anything. So for now, for most nodes, this isn't possible. Also see #5 for similar discussion. Will reconsider in the future if a more reliable way of detecting this for most/all nodes becomes available.
