### ISSUE TITLE
missing czech clients from map.czmesh.cz

### ISSUE THREAD

**Issue by Howardzi-nn** [brianshea2/meshmap.net#28]
Hi,
in the Czech Republic we use
https://map.czmesh.cz/
(https://czmesh.cz/)
![image](https://github.com/user-attachments/assets/bbc1dc11-7d36-4e66-b43d-fb46503010ef)

I'm not sure why the https://meshmap.net/ map doesn't show a single client from the Czech Republic?
![image](https://github.com/user-attachments/assets/3a76a522-0270-4bc5-ae87-32c9a27f90cf)

may its not issue or relevant spot to ask, sorry if it so

**Comment by brianshea2** [comment]
I'm guessing most of those MQTT-connected nodes are reporting to a non-default, non-LoRa-region-based root topic. Unable to confirm since the linked map seems broken -- all "MQTT connected" nodes show no packets (and no topic) in their details.
