### ISSUE TITLE
differentiate node regions

### ISSUE THREAD

**Issue by bialystok** [brianshea2/meshmap.net#5]
On this map all bands are looklike this same. Please make different color or 3 buttons

- 433 only
- 433 and [915/868]
- 868 only

**Comment by brianshea2** [comment]
It's currently not possible to determine the radio region for most nodes on the map. That data is only available in map report messages, and not provided from nodes heard over LoRa. If that ever changes, this would be a great addition.

**Comment by bialystok** [comment]
Each node contains the information 'Region'

on root is 'msh/EU_868/SK' or similar. The point is , the map is there for us to see if the area is already covered. And if these are two different radio bands, it is confusing.

**Comment by brianshea2** [comment]
Only the MapReport messages contain the true region settings. The default region-based root topic is user-modifiable and is that of the MQTT-connected node, not necessarily reflecting the region of the nodes being reported through that node. For those reasons, I don't consider the root topic a viable source for a node's region.

**Comment by brianshea2** [comment]
Until a more reliable and common way is implemented to report the region, node owners may consider adding the region to their long name in areas where multiple radio regions may exist.

**Comment by brianshea2** [comment]
Closing for now. Will reconsider in the future if a better source of this information becomes available.
