### ISSUE TITLE
power

### ISSUE THREAD

**Issue by bialystok** [brianshea2/meshmap.net#6]
What do you think about trying to put information on the map about how the nodes are powered?
The idea is to know if the nodes are current autonomous or not.

I suggest that the name of the node should start with **~** if it is powered by the power grid or **|** if it is powered by solar panels. You can also set a root mqtt name.

**Comment by brianshea2** [comment]
The node details popup will display if a node is plugged in (or its battery level otherwise) if supported and reported by that node. Some nodes may need their ADC multiplier power setting adjusted.

**Comment by 128element** [comment]
> The node details popup will display if a node is plugged in

this is not exactly this same. offgrid or not offgrid is veryimportant in emergency situation

**Comment by brianshea2** [comment]
The on/off-grid-ness is a neat idea, but not a separate field currently. This would be good information for node owners to include in the node long name.

**Comment by brianshea2** [comment]
Closing for now. Will reconsider in the future if this piece of information becomes part of the node database.
