### ISSUE TITLE
Show shortname instead of just a dot.

### ISSUE THREAD

**Issue by cyberorg** [brianshea2/meshmap.net#9]
Hi, would it be possible to show shortname instead of just a dot?

See this for example: https://meshtastic.taubetele.com/
https://github.com/kkwestt/meshtastic.taubetele.com

Cheers

Also requested on: https://github.com/liamcottle/meshtastic-map/issues/39

**Comment by brianshea2** [comment]
Shortnames (and last updated time) are part of the (new) tooltip shown when hovering on a marker. I did try making those always shown, but it quickly became too crowded in my opinion. I may make that an option for people who want them always shown, but for now, I think it's better to keep the map less cluttered.
